#!/usr/bin/zsh
URL=https://github.com/grunwmar/dotfiles.git
DOTFILES=$HOME/.dotfiles
git clone $URL $DOTFILES
cd $DOTFILES
./distribute.py

echo ""
echo ""
echo "To install referenced packages and do commands referenced in 'packages.toml' run"
echo "  cd ~/.dotfiles"
echo "  ./install.py"

sleep 5
clear ; exec zsh
