#!/usr/bin/zsh
URL=https://github.com/grunwmar/dotfiles.git
DOTFILES=$HOME/.dotfiles
git clone $URL $DOTFILES
cd $DOTFILES
./distribute.py
sleep 10
clear

echo ""
echo "To install referenced packages and do commands referenced in 'packages.toml' run"
echo "  cd ~/.dotfiles"
echo "  ./install.py"
echo ""
echo ""
echo "Now wait for 5 sec, then zshell will be re-executed."

sleep 5
clear ; exec zsh
